### ISSUE TITLE
Project Outdated

### ISSUE THREAD

**Issue by kanpuriyanawab** [alexcg1/example-chatbot#1]
Hi @alexcg1 , this is a very interesting usecase I came across as I'm just getting started with Jina.
But when I tried to run the project, it threw lots of deprecation warnings, which I'm unable to fix, being a beginner. 

Therefore I would request you to update this project?
or is there any similar project which runs on latest jina ?

Thanks

**Comment by alexcg1** [comment]
Hey there,

Yeah, it's been ages since I touched this code, so it likely won't run. And I don't have capacity to fix it right now :frowning_face: 

However, deprecation warnings are no big deal. They're just saying "this particular feature of a library is planned to be changed/discontinued in future". I see them all the time when I'm running stuff just fine.
